//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beadando_f9zw0q.Adatbázis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termék
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Termék()
        {
            this.Rendelés = new HashSet<Rendelés>();
        }
    
        public int TermékID { get; set; }
        public Nullable<int> RuhadarabFK { get; set; }
        public Nullable<int> MéretFK { get; set; }
        public Nullable<int> SzínFK { get; set; }
        public Nullable<int> FazonFK { get; set; }
    
        public virtual Fazon Fazon { get; set; }
        public virtual Méret Méret { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendelés> Rendelés { get; set; }
        public virtual Ruhadarab Ruhadarab { get; set; }
        public virtual Szín Szín { get; set; }
    }
}
