//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beadando_f9zw0q
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendelés
    {
        public int RendelésID { get; set; }
        public Nullable<int> TermékFK { get; set; }
        public string Név { get; set; }
    
        public virtual Termék Termék { get; set; }
    }
}
